FROM python:3.11

WORKDIR /app

# Poetry 설치
RUN pip install poetry

# Poetry 가상 환경 비활성화 (Docker 내부에서는 불필요)
RUN poetry config virtualenvs.create false

# 의존성 파일 복사
COPY pyproject.toml poetry.lock ./

# 의존성 설치
RUN poetry install --no-dev

# 소스 코드 복사
COPY . .

RUN chmod +x start-api.sh

CMD ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]