version: '3.8'

services:
  api:
    build: .
    container_name: marathon_api
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}  # db 서비스를 가리킴
      - POSTGRES_PORT=${DB_PORT}
    depends_on:
      - db
    volumes:
      - .:/app  
    
  db:
    image: postgres:14
    container_name: marathon_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: